In [1]:
import numpy as np
import pandas as pd
import torch
from tqdm import tqdm

In [2]:
df_rna = pd.read_csv('../../results/cell_type_embedding/rna_pca.csv', index_col=0)
df_rna['cell_type'] = df_rna.index
df_rna.reset_index(drop=True, inplace=True)
df_rna.head()

,PCA_0,PCA_1,PCA_2,PCA_3,PCA_4,PCA_5,PCA_6,PCA_7,PCA_8,PCA_9,PCA_10,PCA_11,PCA_12,PCA_13,PCA_14,cell_type
0,-0.116944,6.797616,0.141448,-0.010329,0.209467,-0.110409,-0.054209,-0.089452,0.014788,0.159434,-0.066586,-0.215790,0.092058,0.071354,-0.085981,B cells
1,7.054492,-1.097528,-0.381173,0.438082,-0.087500,0.103286,-0.078048,0.022110,-0.029509,-0.043606,0.012369,0.094361,-0.003509,0.040294,-0.011380,Myeloid cells
2,-2.523751,-1.458417,3.552889,0.187137,0.245377,0.247587,-0.047436,-0.024522,-0.069554,-0.238218,0.124646,-0.017130,-0.005766,0.075384,-0.106673,NK cells
3,-3.527583,-1.223455,-1.407943,-0.087279,-0.105173,-0.166271,-0.014173,-0.047556,0.016597,0.097814,0.064968,0.024253,0.095496,-0.021572,0.030785,T cells CD4+
4,-3.500110,-1.045721,-1.653474,-0.132634,-0.041570,0.647838,0.107944,-0.489130,-0.747345,-0.895747,-0.213665,-0.943113,-0.322815,0.163602,0.141510,T cells CD8+

In [3]:
for cell_type in ['nk', 't_cd4', 't_cd8', 't_reg']:
    print(cell_type)
    
    df_train = pd.read_csv(f'../../results/PerturbNet/splited_data/train_{cell_type}.csv')
    df_valid = pd.read_csv(f'../../results/PerturbNet/splited_data/valid_{cell_type}.csv')
    
    df = pd.merge(df_train, df_rna, on='cell_type', how='left')
    
    train_x = df.iloc[:, 5:].values
    
    df = pd.merge(df_valid, df_rna, on='cell_type', how='left')
    valid_x = df.iloc[:, 5:].values
    
    np.savez(f'../../results/PerturbNet/cell_type_embedding_rna/train_{cell_type}.npz', x=train_x)
    np.savez(f'../../results/PerturbNet/cell_type_embedding_rna/valid_{cell_type}.npz', x=valid_x)

nk
t_cd4
t_cd8
t_reg

In [4]:
df_test = pd.read_csv(f'../../results/PerturbNet/splited_data/test.csv')
df = pd.merge(df_test, df_rna, on='cell_type', how='left')

test_x = df.iloc[:, 5:].values
np.savez(f'../../results/PerturbNet/cell_type_embedding_rna/test.npz', x=test_x)

In [5]:
df_atac = pd.read_csv('../../results/cell_type_embedding/atac_nmf.csv', index_col=0)
df_atac['cell_type'] = df_atac.index
df_atac.reset_index(drop=True, inplace=True)
df_atac.head()

,NMF_0,NMF_1,NMF_2,NMF_3,NMF_4,NMF_5,NMF_6,NMF_7,NMF_8,NMF_9,NMF_10,NMF_11,NMF_12,NMF_13,NMF_14,cell_type
0,0.018592,0.003025,0.050563,0.001345,0.001006,0.015570,0.029106,0.002474,0.002662,0.001973,0.005991,0.003509,0.001583,0.002197,0.001657,B cells
1,0.009754,0.029612,0.002666,0.001079,0.001143,0.008272,0.002876,0.002198,0.004565,0.030104,0.002493,0.001972,0.001256,0.001219,0.017573,Myeloid cells
2,0.018087,0.000879,0.001885,0.026569,0.012312,0.014297,0.001601,0.023245,0.002490,0.001352,0.009192,0.004535,0.004625,0.022688,0.000782,NK cells
3,0.019644,0.000933,0.002302,0.004219,0.012129,0.016584,0.001587,0.002779,0.002747,0.001399,0.019274,0.025508,0.021145,0.010545,0.000649,T cells CD4+
4,0.019397,0.000470,0.003770,0.002388,0.005272,0.017887,0.001430,0.004696,0.002304,0.001281,0.008345,0.043694,0.007764,0.010807,0.000848,T cells CD8+

In [6]:
for cell_type in ['nk', 't_cd4', 't_cd8', 't_reg']:
    print(cell_type)
    
    df_train = pd.read_csv(f'../../results/PerturbNet/splited_data/train_{cell_type}.csv')
    df_valid = pd.read_csv(f'../../results/PerturbNet/splited_data/valid_{cell_type}.csv')
    
    df = pd.merge(df_train, df_atac, on='cell_type', how='left')
    
    train_x = df.iloc[:, 5:].values
    
    df = pd.merge(df_valid, df_atac, on='cell_type', how='left')
    valid_x = df.iloc[:, 5:].values
    
    np.savez(f'../../results/PerturbNet/cell_type_embedding_atac/train_{cell_type}.npz', x=train_x)
    np.savez(f'../../results/PerturbNet/cell_type_embedding_atac/valid_{cell_type}.npz', x=valid_x)

nk
t_cd4
t_cd8
t_reg

In [7]:
df_test = pd.read_csv(f'../../results/PerturbNet/splited_data/test.csv')
df = pd.merge(df_test, df_rna, on='cell_type', how='left')

test_x = df.iloc[:, 5:].values
np.savez(f'../../results/PerturbNet/cell_type_embedding_atac/test.npz', x=test_x)

In [8]:
# df_embedding = df_rna.merge(df_atac)

In [9]:
# df_embedding.set_index('cell_type', inplace=True)